Repository Pudin-con-pasas-uwu/ecomerce3, pull requests merged in 2023-04, with the labels that each got.

#19 Correcciones F/MN
  .env
  src/components/footer.jsx
  src/components/mailchimp.jsx
  src/components/monthly.jsx
  src/pages/_app.js
  src/pages/api/hello.js
  src/styles/footer.module.css
  src/styles/globals.css
  src/styles/inicio.css
  src/styles/monthly.module.css
Labels: documentation, enhancement

#23 pequeños cambios en la ui-design
  src/components/Checkout/pagostitle.jsx
  src/components/Contact_us/main_contacts.jsx
  src/components/Contact_us/titulo_contact.jsx
  src/components/Navpage.jsx
  src/components/Products/Products_title.jsx
  src/components/Products/cardsection.jsx
  src/components/Products/menunav.jsx
  src/components/about_us/OurTeamTitle.jsx
  src/components/about_us/aboutimg.jsx
  src/components/about_us/aboutlifestory.jsx
  src/components/about_us/aboutourphilosophy.jsx
  src/components/about_us/aboutustitulo.jsx
  src/components/footer.jsx
  src/components/homeblog/space.jsx
  src/components/monthly.jsx
  src/images/exa2.jpg
  src/images/exa21.jpg
  src/images/example.jpg
  src/images/example1.jpg
  src/pages/DetailProducts/[id].js
  src/styles/butomSelectProducts.module.css
  src/styles/globals.css
  src/styles/monthly.module.css
  src/styles/pagos.css
Labels: enhancement, good first issue

#21 Cambios en login
  src/components/login_register/LoginPage.jsx
  src/components/login_register/RegisterPage.jsx
  src/styles/Login&Register.css
Labels: enhancement

#22 Correcion menunav a products
  src/components/Products/categoriesPr.jsx
  src/components/Products/menunav.jsx
  src/images/IMG_0874.jpg
  src/pages/CategoriesP/[id].js
  src/styles/menuCategory.css
Labels: documentation

#24 Logout
  src/components/Navpage.jsx
  src/components/login_register/LoginPage.jsx
  src/pages/LogoutPage2.js
Labels: enhancement

#25 Actualización Footer/Monthly
  src/components/footer.jsx
  src/components/monthly.jsx
  src/styles/About.css
  src/styles/footer.module.css
  src/styles/globals.css
  src/styles/menuCategory.css
  src/styles/monthly.module.css
Labels: documentation, enhancement

#27 carrito
  public/imgs/Ejemplo.jpg
  src/components/Carrito.jsx
  src/components/Layouts/Layout.jsx
  src/components/Navpage.jsx
  src/components/componentsDetaillProducts/ButtomAddCarrito.jsx
  src/components/componentsDetaillProducts/ButtomBak.jsx
  src/components/componentsDetaillProducts/imgProductsCart.jsx
  src/pages/DetailProducts/[id].js
  src/pages/_app.js
  src/pages/cart.js
  src/styles/butomSelectProducts.module.css
  utils/Store.js
Labels: documentation

#29 se mejoro el carrito
  src/components/Navpage.jsx
  src/components/Products/menunav.jsx
  src/components/componentsDetaillProducts/imgProductsCart.jsx
  src/components/footer.jsx
  src/pages/CategoriesP/[id].js
  src/pages/DetailProducts/[id].js
  src/pages/Productos.js
  src/pages/cart.js
  src/styles/butomSelectProducts.module.css
Labels: documentation

#28 cambio de responsive en el conatact us
  src/styles/ContactUs.css
Labels: enhancement

#30 pequenos cambios
  src/components/about_us/aboutimg.jsx
  src/images/exa1.jpg
  src/styles/About.css
  src/styles/globals.css
Labels: documentation

#31 Cambios responsivo
  src/components/footer.jsx
  src/components/monthly.jsx
  src/styles/footer.module.css
  src/styles/globals.css
  src/styles/monthly.module.css
Labels: documentation

#34 cambios pequeños
  src/components/Checkout/pagos_form.jsx
  src/components/componentsDetaillProducts/descriptionProducts.jsx
  src/pages/DetailProducts/[id].js
  src/pages/cart.js
  src/styles/butomSelectProducts.module.css
Labels: documentation

#37 correcion card img
  src/components/about_us/aboutimg.jsx
  src/images/IMG_0874.jpg
  src/images/front_arias.jpg
  src/images/front_casanova.png
  src/images/front_eddy.png
  src/images/front_estrella.jpg
  src/images/front_guillen.jpg
  src/images/front_juan_lider.png
  src/images/front_rivera.jpg
  src/styles/AboutOurTeam.css
Labels: bug

#36 Responsivo Footer
  src/components/footer.jsx
  src/styles/footer.module.css
  src/styles/globals.css
Labels: documentation
